In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'D:\Python\Ames Housing regression model\Ames_clean_data.csv')

In [3]:
df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,3,2010,WD,Normal,189900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 77 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2925 non-null   int64
 1   MS SubClass      2925 non-null   int64
 2   MS Zoning        2925 non-null   object
 3   Lot Frontage     2925 non-null   float64
 4   Lot Area         2925 non-null   int64
 5   Street           2925 non-null   object
 6   Lot Shape        2925 non-null   object
 7   Land Contour     2925 non-null   object
 8   Utilities        2925 non-null   object
 9   Lot Config       2925 non-null   object
 10  Land Slope       2925 non-null   object
 11  Neighborhood     2925 non-null   object
 12  Condition 1      2925 non-null   object
 13  Condition 2      2925 non-null   object
 14  Bldg Type        2925 non-null   object
 15  House Style      2925 non-null   object
 16  Overall Qual     2925 non-null   int64
 17  Overall Cond     2925 non-null   int64
 18  Year Built       2925 non-null   int64
 19  Year Remod/Add   2925 non-null   int64
 20  Roof Style       2925 non-null   object
 21  Roof Matl        2925 non-null   object
 22  Exterior 1st     2925 non-null   object
 23  Exterior 2nd     2925 non-null   object
 24  Mas Vnr Type     1152 non-null   object
 25  Mas Vnr Area     2925 non-null   float64
 26  Exter Qual       2925 non-null   object
 27  Exter Cond       2925 non-null   object
 28  Foundation       2925 non-null   object
 29  Bsmt Qual        2845 non-null   object
 30  Bsmt Cond        2845 non-null   object
 31  Bsmt Exposure    2842 non-null   object
 32  BsmtFin Type 1   2845 non-null   object
 33  BsmtFin SF 1     2925 non-null   float64
 34  BsmtFin Type 2   2844 non-null   object
 35  BsmtFin SF 2     2925 non-null   float64
 36  Bsmt Unf SF      2925 non-null   float64
 37  Total Bsmt SF    2925 non-null   float64
 38  Heating          2925 non-null   object
 39  Heating QC       2925 non-null   object
 40  Central Air      2925 non-null   object
 41  Electrical       2925 non-null   object
 42  1st Flr SF       2925 non-null   int64
 43  2nd Flr SF       2925 non-null   int64
 44  Low Qual Fin SF  2925 non-null   int64
 45  Gr Liv Area      2925 non-null   int64
 46  Bsmt Full Bath   2925 non-null   float64
 47  Bsmt Half Bath   2925 non-null   float64
 48  Full Bath        2925 non-null   int64
 49  Half Bath        2925 non-null   int64
 50  Bedroom AbvGr    2925 non-null   int64
 51  Kitchen AbvGr    2925 non-null   int64
 52  Kitchen Qual     2925 non-null   object
 53  TotRms AbvGrd    2925 non-null   int64
 54  Functional       2925 non-null   object
 55  Fireplaces       2925 non-null   int64
 56  Fireplace Qu     1505 non-null   object
 57  Garage Type      2768 non-null   object
 58  Garage Yr Blt    2925 non-null   float64
 59  Garage Finish    2767 non-null   object
 60  Garage Cars      2925 non-null   float64
 61  Garage Area      2925 non-null   float64
 62  Garage Qual      2767 non-null   object
 63  Garage Cond      2767 non-null   object
 64  Paved Drive      2925 non-null   object
 65  Wood Deck SF     2925 non-null   int64
 66  Open Porch SF    2925 non-null   int64
 67  Enclosed Porch   2925 non-null   int64
 68  3Ssn Porch       2925 non-null   int64
 69  Screen Porch     2925 non-null   int64
 70  Pool Area        2925 non-null   int64
 71  Misc Val         2925 non-null   int64
 72  Mo Sold          2925 non-null   int64
 73  Yr Sold          2925 non-null   int64
 74  Sale Type        2925 non-null   object
 75  Sale Condition   2925 non-null   object
 76  SalePrice        2925 non-null   int64
dtypes: float64(11), int64(27), object(39)
memory usage: 1.7+ MB

In [5]:
# Converting a numeric column to a categorical

In [6]:
df['MS SubClass'] =  df['MS SubClass'].apply(str)

In [7]:
df.select_dtypes(include=object)

,MS SubClass,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,...,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,20,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,TA,Typ,Gd,Attchd,Fin,TA,TA,P,WD,Normal
1,20,RH,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,...,TA,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
2,20,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Gd,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
3,20,RL,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,...,Ex,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal
4,60,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,TA,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,80,RL,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,Mitchel,Norm,...,TA,Typ,NaN,Detchd,Unf,TA,TA,Y,WD,Normal
2921,20,RL,Pave,IR1,Low,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,NaN,Attchd,Unf,TA,TA,Y,WD,Normal
2922,85,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,...,TA,Typ,NaN,NaN,NaN,NaN,NaN,Y,WD,Normal
2923,20,RL,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,TA,Attchd,RFn,TA,TA,Y,WD,Normal
2924,60,RL,Pave,Reg,Lvl,AllPub,Inside,Mod,Mitchel,Norm,...,TA,Typ,TA,Attchd,Fin,TA,TA,Y,WD,Normal

In [8]:
df_obj = df.select_dtypes(include = object)
df_num = df.select_dtypes(exclude = object)

In [9]:
df_obj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 40 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MS SubClass     2925 non-null   object
 1   MS Zoning       2925 non-null   object
 2   Street          2925 non-null   object
 3   Lot Shape       2925 non-null   object
 4   Land Contour    2925 non-null   object
 5   Utilities       2925 non-null   object
 6   Lot Config      2925 non-null   object
 7   Land Slope      2925 non-null   object
 8   Neighborhood    2925 non-null   object
 9   Condition 1     2925 non-null   object
 10  Condition 2     2925 non-null   object
 11  Bldg Type       2925 non-null   object
 12  House Style     2925 non-null   object
 13  Roof Style      2925 non-null   object
 14  Roof Matl       2925 non-null   object
 15  Exterior 1st    2925 non-null   object
 16  Exterior 2nd    2925 non-null   object
 17  Mas Vnr Type    1152 non-null   object
 18  Exter Qual      2925 non-null   object
 19  Exter Cond      2925 non-null   object
 20  Foundation      2925 non-null   object
 21  Bsmt Qual       2845 non-null   object
 22  Bsmt Cond       2845 non-null   object
 23  Bsmt Exposure   2842 non-null   object
 24  BsmtFin Type 1  2845 non-null   object
 25  BsmtFin Type 2  2844 non-null   object
 26  Heating         2925 non-null   object
 27  Heating QC      2925 non-null   object
 28  Central Air     2925 non-null   object
 29  Electrical      2925 non-null   object
 30  Kitchen Qual    2925 non-null   object
 31  Functional      2925 non-null   object
 32  Fireplace Qu    1505 non-null   object
 33  Garage Type     2768 non-null   object
 34  Garage Finish   2767 non-null   object
 35  Garage Qual     2767 non-null   object
 36  Garage Cond     2767 non-null   object
 37  Paved Drive     2925 non-null   object
 38  Sale Type       2925 non-null   object
 39  Sale Condition  2925 non-null   object
dtypes: object(40)
memory usage: 914.2+ KB

In [10]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2925 non-null   int64
 1   Lot Frontage     2925 non-null   float64
 2   Lot Area         2925 non-null   int64
 3   Overall Qual     2925 non-null   int64
 4   Overall Cond     2925 non-null   int64
 5   Year Built       2925 non-null   int64
 6   Year Remod/Add   2925 non-null   int64
 7   Mas Vnr Area     2925 non-null   float64
 8   BsmtFin SF 1     2925 non-null   float64
 9   BsmtFin SF 2     2925 non-null   float64
 10  Bsmt Unf SF      2925 non-null   float64
 11  Total Bsmt SF    2925 non-null   float64
 12  1st Flr SF       2925 non-null   int64
 13  2nd Flr SF       2925 non-null   int64
 14  Low Qual Fin SF  2925 non-null   int64
 15  Gr Liv Area      2925 non-null   int64
 16  Bsmt Full Bath   2925 non-null   float64
 17  Bsmt Half Bath   2925 non-null   float64
 18  Full Bath        2925 non-null   int64
 19  Half Bath        2925 non-null   int64
 20  Bedroom AbvGr    2925 non-null   int64
 21  Kitchen AbvGr    2925 non-null   int64
 22  TotRms AbvGrd    2925 non-null   int64
 23  Fireplaces       2925 non-null   int64
 24  Garage Yr Blt    2925 non-null   float64
 25  Garage Cars      2925 non-null   float64
 26  Garage Area      2925 non-null   float64
 27  Wood Deck SF     2925 non-null   int64
 28  Open Porch SF    2925 non-null   int64
 29  Enclosed Porch   2925 non-null   int64
 30  3Ssn Porch       2925 non-null   int64
 31  Screen Porch     2925 non-null   int64
 32  Pool Area        2925 non-null   int64
 33  Misc Val         2925 non-null   int64
 34  Mo Sold          2925 non-null   int64
 35  Yr Sold          2925 non-null   int64
 36  SalePrice        2925 non-null   int64
dtypes: float64(11), int64(26)
memory usage: 845.6 KB

In [11]:
df_obj = pd.get_dummies(df_obj, drop_first= True).astype(int)

In [12]:
final_df = pd.concat([df_num,df_obj], axis = 1) # hmerging both the datasets

In [13]:
final_df

,PID,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,526301100,141.000000,31770,6,5,1960,1960,112.0,639.0,0.0,...,0,0,0,0,1,0,0,0,1,0
1,526350040,80.000000,11622,5,6,1961,1961,0.0,468.0,144.0,...,0,0,0,0,1,0,0,0,1,0
2,526351010,81.000000,14267,6,6,1958,1958,108.0,923.0,0.0,...,0,0,0,0,1,0,0,0,1,0
3,526353030,93.000000,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,1,0,0,0,1,0
4,527105010,74.000000,13830,5,5,1997,1998,0.0,791.0,0.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,923275080,37.000000,7937,6,6,1984,1984,0.0,819.0,0.0,...,0,0,0,0,1,0,0,0,1,0
2921,923276100,75.144444,8885,5,5,1983,1983,0.0,301.0,324.0,...,0,0,0,0,1,0,0,0,1,0
2922,923400125,62.000000,10441,5,5,1992,1992,0.0,337.0,0.0,...,0,0,0,0,1,0,0,0,1,0
2923,924100070,77.000000,10010,5,5,1974,1975,0.0,1071.0,123.0,...,0,0,0,0,1,0,0,0,1,0
2924,924151050,74.000000,9627,7,5,1993,1994,94.0,758.0,0.0,...,0,0,0,0,1,0,0,0,1,0

In [14]:
final_df.to_csv(r'Ames_Final Dataset.csv')